project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default

execute:
  freeze: true

editor: visual

title: KTS complicated by KMS during pregnancy

bibliography: references.bib
csl: vancouver.csl

